config/routes.rb
Rails.application.routes.draw do
  resources :superheros

  root 'pages#home'
  use_doorkeeper
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  draw :api

end

app/models/superhero.rb
class Superhero < ApplicationRecord
end

app/controllers/api/v1/superheros_controller.rb
class Api::V1::SuperherosController < ApiController
  before_action :set_superhero, only: %i[ show edit update destroy ]

  # GET /superheros or /superheros.json
  def index
    @superheros = Superhero.all.order(created_at: :desc)
    render json: @superheros
  end

  # GET /superheros/1 or /superheros/1.json
  def show
    render json: @superhero
  end

  # GET /superheros/new
  def new
    @superhero = Superhero.new
  end

  # GET /superheros/1/edit
  def edit
  end

  # POST /superheros or /superheros.json
  def create
    @superhero = Superhero.new(superhero_params)
      if @superhero.save
        render json: @superhero, status: :created, location: @superhero
      else
        render json: @superhero.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /superheros/1 or /superheros/1.json
  def update
    if @superhero.update(superhero_params)
      render json: @superhero
    else
      render json: @superhero.errors, status: :unprocessable_entity
      end
  end

  # DELETE /superheros/1 or /superheros/1.json
  def destroy
    @superhero.destroy
    if @superhero.destroy
      head :no_content
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_superhero
      @superhero = Superhero.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def superhero_params
      params.require(:superhero).permit(:name, :power, :prefix, :suffix, :descriptor)
    end
end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
  before_action :set_superhero, only: %i[ show edit update destroy ]

  # GET /superheros or /superheros.json
  def index
    @superheros = Superhero.all.order(created_at: :desc)
  end

  # GET /superheros/1 or /superheros/1.json
  def show
  end

  # GET /superheros/new
  def new
    @superhero = Superhero.new
  end

  # GET /superheros/1/edit
  def edit
  end

  # POST /superheros or /superheros.json
  def create
    @superhero = Superhero.new(superhero_params)

    respond_to do |format|
      if @superhero.save
        format.html { redirect_to superhero_url(@superhero), notice: "Superhero was successfully created." }
        format.json { render :show, status: :created, location: @superhero }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @superhero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /superheros/1 or /superheros/1.json
  def update
    respond_to do |format|
      if @superhero.update(superhero_params)
        format.html { redirect_to superhero_url(@superhero), notice: "Superhero was successfully updated." }
        format.json { render :show, status: :ok, location: @superhero }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @superhero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /superheros/1 or /superheros/1.json
  def destroy
    @superhero.destroy

    respond_to do |format|
      format.html { redirect_to superheros_url, notice: "Superhero was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_superhero
      @superhero = Superhero.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def superhero_params
      params.require(:superhero).permit(:name, :power, :prefix, :suffix, :descriptor)
    end
end

app/helpers/superheros_helper.rb
module SuperherosHelper
end

app/views/superheros/_form.html.erb
<%= form_with(model: superhero) do |form| %>
  <% if superhero.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(superhero.errors.count, "error") %> prohibited this superhero from being saved:</h2>

      <ul>
        <% superhero.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :power, style: "display: block" %>
    <%= form.text_field :power %>
  </div>

  <div>
    <%= form.label :prefix, style: "display: block" %>
    <%= form.text_field :prefix %>
  </div>

  <div>
    <%= form.label :suffix, style: "display: block" %>
    <%= form.text_field :suffix %>
  </div>

  <div>
    <%= form.label :descriptor, style: "display: block" %>
    <%= form.text_field :descriptor %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/superheros/_superhero.html.erb
<div id="<%= dom_id superhero %>">
  <p>
    <strong>Name:</strong>
    <%= superhero.name %>
  </p>

  <p>
    <strong>Power:</strong>
    <%= superhero.power %>
  </p>

  <p>
    <strong>Prefix:</strong>
    <%= superhero.prefix %>
  </p>

  <p>
    <strong>Suffix:</strong>
    <%= superhero.suffix %>
  </p>

  <p>
    <strong>Descriptor:</strong>
    <%= superhero.descriptor %>
  </p>

</div>

app/views/superheros/edit.html.erb
<h1>Editing superhero</h1>

<%= render "form", superhero: @superhero %>

<br>

<div>
  <%= link_to "Show this superhero", @superhero %> |
  <%= link_to "Back to superheros", superheros_path %>
</div>

app/views/superheros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Superheros</h1>

<div id="superheros">
  <% @superheros.each do |superhero| %>
    <%= render superhero %>
    <p>
      <%= link_to "Show this superhero", superhero %>
    </p>
  <% end %>
</div>

<%= link_to "New superhero", new_superhero_path %>

app/views/superheros/new.html.erb
<h1>New superhero</h1>

<%= render "form", superhero: @superhero %>

<br>

<div>
  <%= link_to "Back to superheros", superheros_path %>
</div>

app/views/superheros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @superhero %>

<div>
  <%= link_to "Edit this superhero", edit_superhero_path(@superhero) %> |
  <%= link_to "Back to superheros", superheros_path %>

  <%= button_to "Destroy this superhero", @superhero, method: :delete %>
</div>